wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.7
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1695184043.181995
    t:
      1:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 105
      2:
      - 1
      - 41
      - 49
      - 51
      - 55
      - 105
      3:
      - 23
      4: 3.9.7
      5: 0.15.10
      8:
      - 1
      - 2
      - 5
